### ISSUE TITLE
Опять без README?

### ISSUE THREAD

**Issue by kotleni** [AlexGyver/MecanumBot#1]
_хых_

**Comment by AlexGyver** [comment]
Ага

**Comment by kotleni** [comment]
Сделать как в прошлый раз?

**Comment by AlexGyver** [comment]
Ну чё народ погнали нах*й

**Comment by kotleni** [comment]
Готово, сэр!

[тут котики и пулл](https://github.com/AlexGyver/MecanumBot/pull/2)
